# Generated by Django 4.1.1 on 2022-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default='CASH', max_length=300, null=True),
        ),
    ]
