# Generated by Django 4.1.1 on 2022-12-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_processed',
            new_name='is_processed',
        ),
    ]
