# Generated by Django 4.1.1 on 2023-01-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_transaction_processed_transaction_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_means',
            field=models.CharField(choices=[('PDQ', 'PDQ'), ('CASH', 'CASH'), ('CARD', 'CARD'), ('WALLET', 'WALLET'), ('MPESA TILL', 'MPESA TILL'), ('MPESA PAYBILL', 'MPESA PAYBILL'), ('BANK WIRE TRANSFER', 'BANK WIRE TRANSFER')], default='CASH', max_length=250),
        ),
    ]
