# Generated by Django 4.1.1 on 2023-01-16 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_means'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
