# Generated by Django 4.0.4 on 2022-09-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='served_by',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
