# Generated by Django 4.0.4 on 2022-09-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='note',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encounter',
            name='stalling_reason',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encounter',
            name='processing_status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('SUCCESS', 'SUCCESS'), ('STALLED', 'STALLED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=300),
        ),
    ]
