# Generated by Django 4.1.1 on 2022-11-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_staff_delete_employee'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_person_staff', to='enterprises.staff'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='served_by_staff', to='enterprises.staff'),
        ),
    ]
