# Generated by Django 4.1.1 on 2022-10-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='processing_status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('BILLING DONE', 'BILLING DONE'), ('SUCCESS', 'SUCCESS'), ('STALLED', 'STALLED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=300),
        ),
    ]
