# Generated by Django 4.0.4 on 2022-09-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_encounter_note_encounter_stalling_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='stalling_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
