# Generated by Django 4.1.1 on 2023-02-08 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_alter_units_units_name_alter_units_units_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('warehouse_code', models.CharField(blank=True, max_length=250, null=True)),
                ('warehouse_name', models.CharField(max_length=300)),
                ('warehouse_type', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('BONDED', 'BONDED'), ('SMART', 'SMART'), ('CONSOLIDATED', 'CONSOLIDATED'), ('COOPERATIVE', 'COOPERATIVE'), ('GOVERNMENT', 'GOVERNMENT'), ('DISTRIBUTION CENTER', 'DISTRIBUTION CENTER')], default='PRIVATE', max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_receiving', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('pushed_to_edi', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
            options={
                'ordering': ['item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseWarehouseItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('pushed_to_edi', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('record_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('opening_quantity', models.FloatField(default=0.0)),
                ('opening_total_amount', models.FloatField(default=0.0)),
                ('warehouse_process', models.CharField(choices=[('RECEIVING', 'RECEIVING'), ('PUT AWAY', 'PUT AWAY'), ('PICKING', 'PICKING'), ('PACKING', 'PACKING'), ('DISPATCHING', 'DISPATCHING'), ('SHIPPING', 'SHIPPING'), ('STORAGE', 'STORAGE'), ('RETURNS', 'RETURNS'), ('VALUE ADDING', 'VALUE ADDING')], default='STORAGE', max_length=300)),
                ('record_type', models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE'), ('TRANSFER', 'TRANSFER')], default='ADD', max_length=300)),
                ('quantity_recorded', models.FloatField()),
                ('removal_type', models.CharField(blank=True, choices=[('INVENTORY', 'INVENTORY'), ('DAMAGES', 'DAMAGES'), ('SUPPLIES', 'SUPPLIES')], max_length=300, null=True)),
                ('removal_guid', models.UUIDField(blank=True, null=True)),
                ('addition_guid', models.UUIDField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('disposing_price', models.FloatField(blank=True, null=True)),
                ('total_amount_recorded', models.FloatField(blank=True, null=True)),
                ('closing_quantity', models.FloatField(blank=True, null=True)),
                ('closing_total_amount', models.FloatField(blank=True, null=True)),
                ('removal_quantity_leaving_warehouse', models.FloatField(blank=True, default=0, null=True)),
                ('removal_quantity_remaining_in_warehouse', models.FloatField(blank=True, default=0, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_items',
            field=models.ManyToManyField(related_name='warehousewarehouseitems', through='warehouses.WarehouseWarehouseItem', to='warehouses.warehouseitem'),
        ),
    ]
