# Generated by Django 4.1.1 on 2022-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
    ]
