# Generated by Django 4.1.1 on 2022-11-25 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_payment_is_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='required_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
