# Generated by Django 4.1.1 on 2022-11-15 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0002_inventoryrecord_updated_catalog'),
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItemAuditLog',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('quantity_before', models.FloatField(default=0)),
                ('quantity_recorded', models.FloatField(default=0)),
                ('quantity_after', models.FloatField(default=0)),
                ('selling_price_before', models.FloatField(default=0)),
                ('selling_price_recorded', models.FloatField(default=0)),
                ('selling_price_after', models.FloatField(default=0)),
                ('marked_price_before', models.FloatField(default=0)),
                ('marked_price_recorded', models.FloatField(default=0)),
                ('marked_price_after', models.FloatField(default=0)),
                ('threshold_price_before', models.FloatField(default=0)),
                ('threshold_price_recorded', models.FloatField(default=0)),
                ('threshold_price_after', models.FloatField(default=0)),
                ('discount_amount_before', models.FloatField(default=0)),
                ('discount_amount_recorded', models.FloatField(default=0)),
                ('discount_amount_after', models.FloatField(default=0)),
                ('record_type', models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE')], max_length=300)),
                ('operation_type', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'CREATE')], max_length=300)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_item_audit_log', to='catalog.catalogitem')),
                ('inventory_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventoryrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
