# Generated by Django 4.0.4 on 2022-09-03 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCatalog',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('quantity', models.FloatField()),
                ('quantity_on_deposit', models.FloatField()),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
