# Generated by Django 4.0.4 on 2022-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='name',
            new_name='catalog_code',
        ),
        migrations.AddField(
            model_name='catalog',
            name='catalog_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
