# Generated by Django 4.1.1 on 2022-11-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalogitemauditlog_audit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='catalog_type',
            field=models.CharField(choices=[('ON SITE', 'ON SITE'), ('AGENTS', 'AGENTS'), ('CUSTOMERS', 'CUSTOMERS')], default='ON SITE', max_length=300),
        ),
    ]
