# Generated by Django 4.1.1 on 2022-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_catalog_catalog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
