# Generated by Django 4.1.1 on 2022-11-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0003_inventory_is_default'),
        ('catalog', '0006_catalog_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitemauditlog',
            name='audit_source',
            field=models.CharField(choices=[('CATALOG ITEM', 'CATALOG ITEM'), ('INVENTORY RECORD', 'INVENTORY RECORD')], default='INVENTORY RECORD', max_length=300),
        ),
        migrations.AlterField(
            model_name='catalogitemauditlog',
            name='inventory_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='debit.inventoryrecord'),
        ),
    ]
