# Generated by Django 4.1.1 on 2022-11-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisesetuprule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
