# Generated by Django 4.1.1 on 2022-11-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisesetuprule',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
