# Generated by Django 4.0.4 on 2022-08-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quantity_to_inventory_in_store',
            new_name='quantity_to_inventory_in_warehouse',
        ),
    ]
