# Generated by Django 4.1.1 on 2022-10-23 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='move_in_bulk',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity_purchased',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity_to_inventory',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity_to_inventory_in_warehouse',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity_to_inventory_on_display',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='recommended_retail_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='sale_units_purchased',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('quantity_returned', models.FloatField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('item', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('quantity_purchased', models.FloatField()),
                ('sale_units_purchased', models.FloatField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recommended_retail_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_to_inventory', models.FloatField(blank=True, null=True)),
                ('quantity_to_inventory_on_display', models.FloatField(blank=True, null=True)),
                ('quantity_to_inventory_in_warehouse', models.FloatField(blank=True, null=True)),
                ('move_in_bulk', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('purchase', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_purchase', to='credit.purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
