# Generated by Django 4.1.1 on 2022-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='added_to_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
