# Generated by Django 4.1.1 on 2022-10-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0002_purchasesreturn'),
        ('credit', '0002_remove_purchase_item_remove_purchase_move_in_bulk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='sale',
            field=models.ForeignKey(default=0, max_length=250, on_delete=django.db.models.deletion.PROTECT, to='debit.sale'),
            preserve_default=False,
        ),
    ]
