# Generated by Django 4.1.1 on 2022-11-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_salesreturn_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
