# Generated by Django 4.1.1 on 2022-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_purchaseitem_added_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='total_quantity_puchased',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
