# Generated by Django 4.1.1 on 2022-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_purchaseitem_total_quantity_puchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='total_quantity_puchased',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
