# Generated by Django 4.1.1 on 2022-11-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0006_rename_salerecord_saleitem'),
        ('credit', '0004_salesreturn_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='item',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, to='debit.saleitem'),
        ),
    ]
