# Generated by Django 4.1.1 on 2022-11-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_salesreturn_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesreturn',
            old_name='item',
            new_name='sale_item',
        ),
    ]
