# Generated by Django 4.1.1 on 2023-02-08 09:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('invoice_number', models.CharField(blank=True, max_length=300, null=True)),
                ('purchase_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('quantity_purchased', models.FloatField()),
                ('total_quantity_puchased', models.FloatField(blank=True, null=True)),
                ('sale_units_purchased', models.FloatField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recommended_retail_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_to_inventory', models.FloatField(blank=True, default=0, null=True)),
                ('quantity_to_inventory_on_display', models.FloatField(blank=True, default=0, null=True)),
                ('quantity_to_inventory_in_warehouse', models.FloatField(blank=True, default=0, null=True)),
                ('move_in_bulk', models.BooleanField(default=False)),
                ('added_to_warehouse', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('quantity_returned', models.FloatField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('note', models.TextField(blank=True, null=True)),
                ('return_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
