# Generated by Django 4.1.1 on 2023-02-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0002_initial'),
        ('procurement', '0001_initial'),
        ('enterprises', '0002_enterprise_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_order',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_enterprise', to='enterprises.enterprise'),
        ),
    ]
