# Generated by Django 4.1.1 on 2023-02-10 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('payment_method', models.CharField(choices=[('PDQ', 'PDQ'), ('CASH', 'CASH'), ('CARD', 'CARD'), ('WALLET', 'WALLET'), ('MPESA TILL', 'MPESA TILL'), ('BANK CHEQUE', 'BANK CHEQUE'), ('MPESA PAYBILL', 'MPESA PAYBILL'), ('BANK WIRE TRANSFER', 'BANK WIRE TRANSFER'), ('BANK DIRECT DEPOSIT', 'BANK DIRECT DEPOSIT')], max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('purchase', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payment', to='credit.purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
