# Generated by Django 4.1.1 on 2022-10-04 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        ('debit', '0001_initial'),
        ('catalog', '0001_initial'),
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSetupRules',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('supports_installment_sales', models.BooleanField(default=False)),
                ('allocated_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_inventory', to='debit.inventory')),
                ('default_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_catalog', to='catalog.catalog')),
                ('default_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_inventory', to='debit.inventory')),
                ('default_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_warehouse', to='warehouses.warehouse')),
                ('master_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_inventory', to='debit.inventory')),
                ('receiving_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_warehouse', to='warehouses.warehouse')),
                ('standard_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_catalog', to='catalog.catalog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSetup',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('setup_name', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
