# Generated by Django 4.0.4 on 2022-09-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_warehouse_is_receiving_and_more'),
        ('enterprises', '0002_agent_employee'),
        ('restrictions_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprisesetup',
            old_name='name',
            new_name='setup_name',
        ),
        migrations.RemoveField(
            model_name='enterprisesetuprules',
            name='landing_warehouse',
        ),
        migrations.AddField(
            model_name='enterprisesetup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprisesetuprules',
            name='receiving_warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_warehouse', to='warehouses.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enterprisesetup',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise'),
        ),
    ]
