# Generated by Django 4.0.4 on 2022-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictions_mgt', '0002_rename_name_enterprisesetup_setup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisesetuprules',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
