# Generated by Django 4.0.4 on 2022-09-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_receiving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouserecord',
            name='warehouse_process',
            field=models.CharField(choices=[('RECEIVING', 'RECEIVING'), ('PUT AWAY', 'PUT AWAY'), ('PICKING', 'PICKING'), ('PACKING', 'PACKING'), ('DISPATCHING', 'DISPATCHING'), ('SHIPPING', 'SHIPPING'), ('STORAGE', 'STORAGE'), ('RETURNS', 'RETURNS'), ('VALUE ADDING', 'VALUE ADDING')], default='STORAGE', max_length=300),
        ),
        migrations.AlterField(
            model_name='warehouserecord',
            name='record_type',
            field=models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE'), ('TRANSFER', 'TRANSFER')], default='ADD', max_length=300),
        ),
    ]
