# Generated by Django 4.0.4 on 2022-09-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_warehouse_is_receiving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
