# Generated by Django 4.1.1 on 2023-02-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        ('enterprise_mgt', '0001_initial'),
        ('enterprises', '0002_enterprise_short_name'),
        ('debit', '0002_initial'),
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisesetuprulewarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='enterprisesetupruleinventory',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debit.inventory'),
        ),
        migrations.AddField(
            model_name='enterprisesetupruleinventory',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise_mgt.enterprisesetuprule'),
        ),
        migrations.AddField(
            model_name='enterprisesetuprulecatalog',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog'),
        ),
        migrations.AddField(
            model_name='enterprisesetuprulecatalog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise_mgt.enterprisesetuprule'),
        ),
        migrations.AddField(
            model_name='enterprisesetuprule',
            name='catalogs',
            field=models.ManyToManyField(related_name='rulecatalog', through='enterprise_mgt.EnterpriseSetupRuleCatalog', to='catalog.catalog'),
        ),
        migrations.AddField(
            model_name='enterprisesetuprule',
            name='inventories',
            field=models.ManyToManyField(related_name='ruleinventory', through='enterprise_mgt.EnterpriseSetupRuleInventory', to='debit.inventory'),
        ),
        migrations.AddField(
            model_name='enterprisesetuprule',
            name='warehouses',
            field=models.ManyToManyField(related_name='rulewarehouse', through='enterprise_mgt.EnterpriseSetupRuleWarehouse', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='enterprisesetup',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise'),
        ),
    ]
