"""Preloaded permissions file."""

BASE_PERMISSIONS_MAPPER = {
    'Add Log Entry': 'admin.add_logentry',
    'Change Log Entry': 'admin.change_logentry',
    'Delete Log Entry': 'admin.delete_logentry',
    'View Log Entry': 'admin.view_logentry',
    'Add Add Group': 'auth.add_group',
    'Add Permission': 'auth.add_permission',
    'Change Group': 'auth.change_group',
    'Change Permission': 'auth.change_permission',
    'Delete Group': 'auth.delete_group',
    'Delete Permission': 'auth.delete_permission',
    'View Group': 'auth.view_group',
    'View Permission': 'auth.view_permission',
    'Add Catalog': 'catalog.add_catalog',
    'Add Catalog Catalog Item': 'catalog.add_catalogcatalogitem',
    'Add Catalog Item': 'catalog.add_catalogitem',
    'Add Section': 'catalog.add_section',
    'Change Catalog': 'catalog.change_catalog',
    'Change Catalog Catalog Item': 'catalog.change_catalogcatalogitem',
    'Change Catalog Item': 'catalog.change_catalogitem',
    'Change Section': 'catalog.change_section',
    'Delete Catalog': 'catalog.delete_catalog',
    'Delete Catalog Catalog Item': 'catalog.delete_catalogcatalogitem',
    'Delete Catalog Item': 'catalog.delete_catalogitem',
    'Delete Section': 'catalog.delete_section',
    'View Catalog': 'catalog.view_catalog',
    'View Catalog Catalog Item': 'catalog.view_catalogcatalogitem',
    'View Catalog Item': 'catalog.view_catalogitem',
    'View Section': 'catalog.view_section',
    'Add Content Type': 'contenttypes.add_contenttype',
    'Change Content Type': 'contenttypes.change_contenttype',
    'Delete Content Type': 'contenttypes.delete_contenttype',
    'View Content Type': 'contenttypes.view_contenttype',
    'Add Purchase': 'credit.add_purchase',
    'Add Purchase Item': 'credit.add_purchaseitem',
    'Add Sales Return': 'credit.add_salesreturn',
    'Change Purchase': 'credit.change_purchase',
    'Change Purchase Item': 'credit.change_purchaseitem',
    'Change Sales Return': 'credit.change_salesreturn',
    'Delete Purchase': 'credit.delete_purchase',
    'Delete Purchase Item': 'credit.delete_purchaseitem',
    'Delete Sales Return': 'credit.delete_salesreturn',
    'View Purchase': 'credit.view_purchase',
    'View Purchase Item': 'credit.view_purchaseitem',
    'View Sales Return': 'credit.view_salesreturn',
    'Add Customer': 'customers.add_customer',
    'Change Customer': 'customers.change_customer',
    'Delete Customer': 'customers.delete_customer',
    'View Customer': 'customers.view_customer',
    'Add Inventory': 'debit.add_inventory',
    'Add Inventory Inventory Item': 'debit.add_inventoryinventoryitem',
    'Add Inventory Item': 'debit.add_inventoryitem',
    'Add Inventory Record': 'debit.add_inventoryrecord',
    'Add Purchases Return': 'debit.add_purchasesreturn',
    'Add Sale': 'debit.add_sale',
    'Add Sale Item': 'debit.add_saleitem',
    'Add Sale Record': 'debit.add_salerecord',
    'Change Inventory': 'debit.change_inventory',
    'Change Inventory Inventory Item': 'debit.change_inventoryinventoryitem',
    'Change Inventory Item': 'debit.change_inventoryitem',
    'Change Inventory Record': 'debit.change_inventoryrecord',
    'Change Purchases Return': 'debit.change_purchasesreturn',
    'Change Sale': 'debit.change_sale',
    'Change Sale Item': 'debit.change_saleitem',
    'Change Sale Record': 'debit.change_salerecord',
    'Delete Inventory': 'debit.delete_inventory',
    'Delete Inventory Inventory Item': 'debit.delete_inventoryinventoryitem',
    'Delete Inventory Item': 'debit.delete_inventoryitem',
    'Delete Inventory Record': 'debit.delete_inventoryrecord',
    'Delete Purchases Return': 'debit.delete_purchasesreturn',
    'Delete Sale': 'debit.delete_sale',
    'Delete Sale Item': 'debit.delete_saleitem',
    'Delete Sale Record': 'debit.delete_salerecord',
    'View Inventory': 'debit.view_inventory',
    'View Inventory Inventory Item': 'debit.view_inventoryinventoryitem',
    'View Inventory Item': 'debit.view_inventoryitem',
    'View Inventory Record': 'debit.view_inventoryrecord',
    'View Purchases Return': 'debit.view_purchasesreturn',
    'View Sale': 'debit.view_sale',
    'View Sale Item': 'debit.view_saleitem',
    'View Sale Record': 'debit.view_salerecord',
    'Add Encounter': 'encounters.add_encounter',
    'Change Encounter': 'encounters.change_encounter',
    'Delete Encounter': 'encounters.delete_encounter',
    'View Encounter': 'encounters.view_encounter',
    'Add Agent': 'enterprises.add_agent',
    'Add Employee': 'enterprises.add_employee',
    'Add Enterprise': 'enterprises.add_enterprise',
    'Add Enterprise Contact': 'enterprises.add_enterprisecontact',
    'Add Platform': 'enterprises.add_platform',
    'Change Agent': 'enterprises.change_agent',
    'Change Employee': 'enterprises.change_employee',
    'Change Enterprise': 'enterprises.change_enterprise',
    'Change Enterprise Contact': 'enterprises.change_enterprisecontact',
    'Change Platform': 'enterprises.change_platform',
    'Delete Agent': 'enterprises.delete_agent',
    'Delete Employee': 'enterprises.delete_employee',
    'Delete Enterprise': 'enterprises.delete_enterprise',
    'Delete Enterprise Contact': 'enterprises.delete_enterprisecontact',
    'Delete Platform': 'enterprises.delete_platform',
    'View Agent': 'enterprises.view_agent',
    'View Employee': 'enterprises.view_employee',
    'View Enterprise': 'enterprises.view_enterprise',
    'View Enterprise Contact': 'enterprises.view_enterprisecontact',
    'View Platform': 'enterprises.view_platform',
    'Add Brand': 'items.add_brand',
    'Add Brand Item Type': 'items.add_branditemtype',
    'Add Category': 'items.add_category',
    'Add Item': 'items.add_item',
    'Add Item Attribute': 'items.add_itemattribute',
    'Add Item Image': 'items.add_itemimage',
    'Add Item Model': 'items.add_itemmodel',
    'Add Item Type': 'items.add_itemtype',
    'Add Item Units': 'items.add_itemunits',
    'Add Units': 'items.add_units',
    'Add Units Item Type': 'items.add_unitsitemtype',
    'Change Brand': 'items.change_brand',
    'Change Brand Item Type': 'items.change_branditemtype',
    'Change Category': 'items.change_category',
    'Change Item': 'items.change_item',
    'Change Item Attribute': 'items.change_itemattribute',
    'Change Item Image': 'items.change_itemimage',
    'Change Item Model': 'items.change_itemmodel',
    'Change Item Type': 'items.change_itemtype',
    'Change Item Units': 'items.change_itemunits',
    'Change Units': 'items.change_units',
    'Change Units Item Type': 'items.change_unitsitemtype',
    'Delete Brand': 'items.delete_brand',
    'Delete Branf Item Type': 'items.delete_branditemtype',
    'Delete Category': 'items.delete_category',
    'Delete Item': 'items.delete_item',
    'Delete Item Attribute': 'items.delete_itemattribute',
    'Delete Item Image': 'items.delete_itemimage',
    'Delete Item Model': 'items.delete_itemmodel',
    'Delete Item Type': 'items.delete_itemtype',
    'Delete Item Units': 'items.delete_itemunits',
    'Delete Units': 'items.delete_units',
    'Delete Units Item Type': 'items.delete_unitsitemtype',
    'View Brand': 'items.view_brand',
    'View Brand Item Type': 'items.view_branditemtype',
    'View Category': 'items.view_category',
    'View Item': 'items.view_item',
    'View Item Attribute': 'items.view_itemattribute',
    'View Item Image': 'items.view_itemimage',
    'View Item Model': 'items.view_itemmodel',
    'View Item Type': 'items.view_itemtype',
    'View Item Units': 'items.view_itemunits',
    'View Units': 'items.view_units',
    'View Units Item Type': 'items.view_unitsitemtype',
    'Add Mpesa Authorization': 'mpesa.add_mpesaauthorization',
    'Change Mpesa Authorization': 'mpesa.change_mpesaauthorization',
    'Delete Mpesa Authorization': 'mpesa.delete_mpesaauthorization',
    'View Mpesa Authorization': 'mpesa.view_mpesaauthorization',
    'Add Cart': 'orders.add_cart',
    'Add Cart Item': 'orders.add_cartitem',
    'Add Installment': 'orders.add_installment',
    'Add Installment Order Item': 'orders.add_installmentsorderitem',
    'Add Instant Order Item': 'orders.add_instantorderitem',
    'Add Order': 'orders.add_order',
    'Add Order Status Log': 'orders.add_orderstatuslog',
    'Add Order Transaction': 'orders.add_ordertransaction',
    'Change Cart': 'orders.change_cart',
    'Change Cart Item': 'orders.change_cartitem',
    'Change Installment': 'orders.change_installment',
    'Change Installment Order Item': 'orders.change_installmentsorderitem',
    'Change Instant Order Item': 'orders.change_instantorderitem',
    'Change Order': 'orders.change_order',
    'Change Order Status Log': 'orders.change_orderstatuslog',
    'Change Order Transaction': 'orders.change_ordertransaction',
    'Delete Cart': 'orders.delete_cart',
    'Delete Cart Item': 'orders.delete_cartitem',
    'Delete Installment': 'orders.delete_installment',
    'Delete Installment Order Item': 'orders.delete_installmentsorderitem',
    'Delete Instant Order Item': 'orders.delete_instantorderitem',
    'Delete Order': 'orders.delete_order',
    'Delete Order Status Log': 'orders.delete_orderstatuslog',
    'Delete Order Transaction': 'orders.delete_ordertransaction',
    'View Cart': 'orders.view_cart',
    'View Cart Item': 'orders.view_cartitem',
    'View Installment': 'orders.view_installment',
    'View Installment Order Item': 'orders.view_installmentsorderitem',
    'View Instant Order Item': 'orders.view_instantorderitem',
    'View Order': 'orders.view_order',
    'View Order Status Log': 'orders.view_orderstatuslog',
    'View Order Transaction': 'orders.view_ordertransaction',
    'Add Enterprise Setup': 'enterprise_mgt.add_enterprisesetup',
    'Add Enterprise Setup Rules': 'enterprise_mgt.add_EnterpriseSetupRule',
    'Change Enterprise Setup': 'enterprise_mgt.change_enterprisesetup',
    'Change Enterprise Setup Rules': 'enterprise_mgt.change_EnterpriseSetupRule',
    'Delete Enterprise Setup': 'enterprise_mgt.delete_enterprisesetup',
    'Delete Enterprise Setup Rules': 'enterprise_mgt.delete_EnterpriseSetupRule',
    'View Enterprise Setup': 'enterprise_mgt.view_enterprisesetup',
    'View Enterprise Setup Rules': 'enterprise_mgt.view_EnterpriseSetupRule',
    'Add Session': 'sessions.add_session',
    'Change Session': 'sessions.change_session',
    'Delete Session': 'sessions.delete_session',
    'View Session': 'sessions.view_session',
    'Add Payment': 'transactions.add_payment',
    'Add Payment Request': 'transactions.add_paymentrequest',
    'Add Transaction': 'transactions.add_transaction',
    'Change Payment': 'transactions.change_payment',
    'Change Payment Request': 'transactions.change_paymentrequest',
    'Change Transaction': 'transactions.change_transaction',
    'Delete Payment': 'transactions.delete_payment',
    'Delete Payment Request': 'transactions.delete_paymentrequest',
    'Delete Transaction': 'transactions.delete_transaction',
    'View Payment': 'transactions.view_payment',
    'View Payment Request': 'transactions.view_paymentrequest',
    'View Transaction': 'transactions.view_transaction',
    'Add Group': 'users.add_group',
    'Add Group Permission': 'users.add_grouppermission',
    'Add Permission': 'users.add_permission',
    'Add Role': 'users.add_role',
    'Add User': 'users.add_user',
    'Add User Role': 'users.add_userrole',
    'Change Group': 'users.change_group',
    'Change Group Permission': 'users.change_grouppermission',
    'Change Permission': 'users.change_permission',
    'Change Role': 'users.change_role',
    'Change User': 'users.change_user',
    'Change User Role': 'users.change_userrole',
    'Delete Group': 'users.delete_group',
    'Delete Group Permission': 'users.delete_grouppermission',
    'Delete Permission': 'users.delete_permission',
    'Delete Role': 'users.delete_role',
    'Delete User': 'users.delete_user',
    'Delete User Role': 'users.delete_userrole',
    'View Group': 'users.view_group',
    'View Group Permission': 'users.view_grouppermission',
    'View Permission': 'users.view_permission',
    'View Role': 'users.view_role',
    'View User': 'users.view_user',
    'View User Role': 'users.view_userrole',
    'Add Anonymouse Wallet': 'wallet.add_anonymouswallet',
    'Add Wallet': 'wallet.add_wallet',
    'Add Wallet Record': 'wallet.add_walletrecord',
    'Change Anonymouse Wallet': 'wallet.change_anonymouswallet',
    'Change Wallet': 'wallet.change_wallet',
    'Change Wallet Record': 'wallet.change_walletrecord',
    'Delete Anonymouse Wallet': 'wallet.delete_anonymouswallet',
    'Delete Wallet': 'wallet.delete_wallet',
    'Delete Wallet Record': 'wallet.delete_walletrecord',
    'View Anonymouse Wallet': 'wallet.view_anonymouswallet',
    'View Wallet': 'wallet.view_wallet',
    'View Wallet Record': 'wallet.view_walletrecord',
    'Add Warehouse': 'warehouses.add_warehouse',
    'Add Warehouse Item': 'warehouses.add_warehouseitem',
    'Add Warehouse Record': 'warehouses.add_warehouserecord',
    'Add Warehouse Warehouse Item': 'warehouses.add_warehousewarehouseitem',
    'Change Warehouse': 'warehouses.change_warehouse',
    'Change Warehouse Item': 'warehouses.change_warehouseitem',
    'Change Warehouse Record': 'warehouses.change_warehouserecord',
    'Change Warehouse Warehouse Item': 'warehouses.change_warehousewarehouseitem',
    'Delete Warehouse': 'warehouses.delete_warehouse',
    'Delete Warehouse Item': 'warehouses.delete_warehouseitem',
    'Delete Warehouse Record': 'warehouses.delete_warehouserecord',
    'Delete Warehouse Warehouse Item': 'warehouses.delete_warehousewarehouseitem',
    'View Warehouse': 'warehouses.view_warehouse',
    'View Warehouse Item': 'warehouses.view_warehouseitem',
    'View Warehouse Record': 'warehouses.view_warehouserecord',
    'View Warehouse Warehouse Item': 'warehouses.view_warehousewarehouseitem'
}
