"""Preloaded permissions file."""

BASE_PERMISSIONS_MAPPER = {
    'View Category Screen': 'category.view_screen',
    'Create Category': 'category.create_category',
    'Read Category': 'category.read_category',
    'Update Category': 'category.update_category',
    'Delete Category': 'category.delete_category',
    'View Item Type Screen': 'item_type.view_screen',
    'Create Item Type': 'item_type.create_item_type',
    'Read Item Type': 'item_type.read_item_type',
    'Update Item Type': 'item_type.update_item_type',
    'Delete Item Type': 'item_type.delete_item_type',
    'View Brand Screen': 'brand.view_screen',
    'Create Brand': 'brand.create_brand',
    'Read Brand': 'brand.read_brand',
    'Update Brand': 'brand.update_brand',
    'Delete Brand': 'brand.delete_brand',
    'View Item Model Screen': 'item_model.view_screen',
    'Create Item Model': 'item_model.create_item_model',
    'Read Item Model': 'item_model.read_item_model',
    'Update Item Model': 'item_model.update_item_model',
    'Delete Item Model': 'item_model.delete_item_model',
    'View Item Screen': 'item.view_screen',
    'Create Item': 'item.create_item',
    'Read Item': 'item.read_item',
    'Update Item': 'item.update_item',
    'Delete Item': 'item.delete_item',
    'View Units Screen': 'units.view_screen',
    'Create Units': 'units.create_units',
    'Read Units': 'units.read_units',
    'Update Units': 'units.update_units',
    'Delete Units': 'units.delete_units',
    'View Item Units Screen': 'item_units.view_screen',
    'Create Item Units': 'item_units.create_item_units',
    'Read Item Units': 'item_units.read_item_units',
    'Update Item Units': 'item_units.update_item_units',
    'Delete Item Units': 'item_units.delete_item_units',
}


PERMS = {
    'admin.add_logentry',
    'admin.change_logentry',
    'admin.delete_logentry',
    'admin.view_logentry',
    'auth.add_group',
    'auth.add_permission',
    'auth.change_group',
    'auth.change_permission',
    'auth.delete_group',
    'auth.delete_permission',
    'auth.view_group',
    'auth.view_permission',
    'catalog.add_catalog',
    'catalog.add_catalogcatalogitem',
    'catalog.add_catalogitem',
    'catalog.add_section',
    'catalog.change_catalog',
    'catalog.change_catalogcatalogitem',
    'catalog.change_catalogitem',
    'catalog.change_section',
    'catalog.delete_catalog',
    'catalog.delete_catalogcatalogitem',
    'catalog.delete_catalogitem',
    'catalog.delete_section',
    'catalog.view_catalog',
    'catalog.view_catalogcatalogitem',
    'catalog.view_catalogitem',
    'catalog.view_section',
    'contenttypes.add_contenttype',
    'contenttypes.change_contenttype',
    'contenttypes.delete_contenttype',
    'contenttypes.view_contenttype',
    'credit.add_purchase',
    'credit.add_purchaseitem',
    'credit.add_salesreturn',
    'credit.change_purchase',
    'credit.change_purchaseitem',
    'credit.change_salesreturn',
    'credit.delete_purchase',
    'credit.delete_purchaseitem',
    'credit.delete_salesreturn',
    'credit.view_purchase',
    'credit.view_purchaseitem',
    'credit.view_salesreturn',
    'customers.add_customer',
    'customers.change_customer',
    'customers.delete_customer',
    'customers.view_customer',
    'debit.add_inventory',
    'debit.add_inventoryinventoryitem',
    'debit.add_inventoryitem',
    'debit.add_inventoryrecord',
    'debit.add_purchasesreturn',
    'debit.add_sale',
    'debit.add_saleitem',
    'debit.add_salerecord',
    'debit.change_inventory',
    'debit.change_inventoryinventoryitem',
    'debit.change_inventoryitem',
    'debit.change_inventoryrecord',
    'debit.change_purchasesreturn',
    'debit.change_sale',
    'debit.change_saleitem',
    'debit.change_salerecord',
    'debit.delete_inventory',
    'debit.delete_inventoryinventoryitem',
    'debit.delete_inventoryitem',
    'debit.delete_inventoryrecord',
    'debit.delete_purchasesreturn',
    'debit.delete_sale',
    'debit.delete_saleitem',
    'debit.delete_salerecord',
    'debit.view_inventory',
    'debit.view_inventoryinventoryitem',
    'debit.view_inventoryitem',
    'debit.view_inventoryrecord',
    'debit.view_purchasesreturn',
    'debit.view_sale',
    'debit.view_saleitem',
    'debit.view_salerecord',
    'encounters.add_encounter',
    'encounters.change_encounter',
    'encounters.delete_encounter',
    'encounters.view_encounter',
    'enterprises.add_agent',
    'enterprises.add_employee',
    'enterprises.add_enterprise',
    'enterprises.add_enterprisecontact',
    'enterprises.add_platform',
    'enterprises.change_agent',
    'enterprises.change_employee',
    'enterprises.change_enterprise',
    'enterprises.change_enterprisecontact',
    'enterprises.change_platform',
    'enterprises.delete_agent',
    'enterprises.delete_employee',
    'enterprises.delete_enterprise',
    'enterprises.delete_enterprisecontact',
    'enterprises.delete_platform',
    'enterprises.view_agent',
    'enterprises.view_employee',
    'enterprises.view_enterprise',
    'enterprises.view_enterprisecontact',
    'enterprises.view_platform',
    'items.add_brand',
    'items.add_branditemtype',
    'items.add_category',
    'items.add_item',
    'items.add_itemattribute',
    'items.add_itemimage',
    'items.add_itemmodel',
    'items.add_itemtype',
    'items.add_itemunits',
    'items.add_units',
    'items.add_unitsitemtype',
    'items.change_brand',
    'items.change_branditemtype',
    'items.change_category',
    'items.change_item',
    'items.change_itemattribute',
    'items.change_itemimage',
    'items.change_itemmodel',
    'items.change_itemtype',
    'items.change_itemunits',
    'items.change_units',
    'items.change_unitsitemtype',
    'items.delete_brand',
    'items.delete_branditemtype',
    'items.delete_category',
    'items.delete_item',
    'items.delete_itemattribute',
    'items.delete_itemimage',
    'items.delete_itemmodel',
    'items.delete_itemtype',
    'items.delete_itemunits',
    'items.delete_units',
    'items.delete_unitsitemtype',
    'items.view_brand',
    'items.view_branditemtype',
    'items.view_category',
    'items.view_item',
    'items.view_itemattribute',
    'items.view_itemimage',
    'items.view_itemmodel',
    'items.view_itemtype',
    'items.view_itemunits',
    'items.view_units',
    'items.view_unitsitemtype',
    'mpesa.add_mpesaauthorization',
    'mpesa.change_mpesaauthorization',
    'mpesa.delete_mpesaauthorization',
    'mpesa.view_mpesaauthorization',
    'orders.add_cart',
    'orders.add_cartitem',
    'orders.add_installment',
    'orders.add_installmentsorderitem',
    'orders.add_instantorderitem',
    'orders.add_order',
    'orders.add_orderstatuslog',
    'orders.add_ordertransaction',
    'orders.change_cart',
    'orders.change_cartitem',
    'orders.change_installment',
    'orders.change_installmentsorderitem',
    'orders.change_instantorderitem',
    'orders.change_order',
    'orders.change_orderstatuslog',
    'orders.change_ordertransaction',
    'orders.delete_cart',
    'orders.delete_cartitem',
    'orders.delete_installment',
    'orders.delete_installmentsorderitem',
    'orders.delete_instantorderitem',
    'orders.delete_order',
    'orders.delete_orderstatuslog',
    'orders.delete_ordertransaction',
    'orders.view_cart',
    'orders.view_cartitem',
    'orders.view_installment',
    'orders.view_installmentsorderitem',
    'orders.view_instantorderitem',
    'orders.view_order',
    'orders.view_orderstatuslog',
    'orders.view_ordertransaction',
    'restrictions_mgt.add_enterprisesetup',
    'restrictions_mgt.add_enterprisesetuprules',
    'restrictions_mgt.change_enterprisesetup',
    'restrictions_mgt.change_enterprisesetuprules',
    'restrictions_mgt.delete_enterprisesetup',
    'restrictions_mgt.delete_enterprisesetuprules',
    'restrictions_mgt.view_enterprisesetup',
    'restrictions_mgt.view_enterprisesetuprules',
    'sessions.add_session',
    'sessions.change_session',
    'sessions.delete_session',
    'sessions.view_session',
    'transactions.add_payment',
    'transactions.add_paymentrequest',
    'transactions.add_transaction',
    'transactions.change_payment',
    'transactions.change_paymentrequest',
    'transactions.change_transaction',
    'transactions.delete_payment',
    'transactions.delete_paymentrequest',
    'transactions.delete_transaction',
    'transactions.view_payment',
    'transactions.view_paymentrequest',
    'transactions.view_transaction',
    'users.add_group',
    'users.add_grouppermission',
    'users.add_permission',
    'users.add_role',
    'users.add_user',
    'users.add_userrole',
    'users.change_group',
    'users.change_grouppermission',
    'users.change_permission',
    'users.change_role',
    'users.change_user',
    'users.change_userrole',
    'users.delete_group',
    'users.delete_grouppermission',
    'users.delete_permission',
    'users.delete_role',
    'users.delete_user',
    'users.delete_userrole',
    'users.view_group',
    'users.view_grouppermission',
    'users.view_permission',
    'users.view_role',
    'users.view_user',
    'users.view_userrole',
    'wallet.add_anonymouswallet',
    'wallet.add_wallet',
    'wallet.add_walletrecord',
    'wallet.change_anonymouswallet',
    'wallet.change_wallet',
    'wallet.change_walletrecord',
    'wallet.delete_anonymouswallet',
    'wallet.delete_wallet',
    'wallet.delete_walletrecord',
    'wallet.view_anonymouswallet',
    'wallet.view_wallet',
    'wallet.view_walletrecord',
    'warehouses.add_warehouse',
    'warehouses.add_warehouseitem',
    'warehouses.add_warehouserecord',
    'warehouses.add_warehousewarehouseitem',
    'warehouses.change_warehouse',
    'warehouses.change_warehouseitem',
    'warehouses.change_warehouserecord',
    'warehouses.change_warehousewarehouseitem',
    'warehouses.delete_warehouse',
    'warehouses.delete_warehouseitem',
    'warehouses.delete_warehouserecord',
    'warehouses.delete_warehousewarehouseitem',
    'warehouses.view_warehouse',
    'warehouses.view_warehouseitem',
    'warehouses.view_warehouserecord',
    'warehouses.view_warehousewarehouseitem'
}
