# Generated by Django 4.1.1 on 2022-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='is_direct_installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
    ]
