# Generated by Django 4.0.4 on 2022-08-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
    ]
