# Generated by Django 4.0.4 on 2022-08-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('debit', '0003_sale_encounter'),
        ('orders', '0002_cart_order_guid_order_sale_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale_guid',
        ),
        migrations.AddField(
            model_name='cart',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encounters.encounter'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='debit.sale'),
        ),
    ]
