# Generated by Django 4.1.1 on 2022-11-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_is_enterprise_cart_on_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_enterprise',
            new_name='on_site',
        ),
    ]
