# Generated by Django 4.0.4 on 2022-09-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_sale_remove_order_sale_guid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sale',
        ),
    ]
