# Generated by Django 4.1.1 on 2022-11-23 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_is_enterprise_order_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentsorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='instantorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
