# Generated by Django 4.1.1 on 2023-01-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_units_units_quantity_units_units_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='units_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='units_quantity',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
