# Generated by Django 4.0.4 on 2022-08-10 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import elites_franchise_portal.common.validators
import elites_franchise_portal.items.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('brand_name', models.CharField(max_length=250)),
                ('brand_code', models.CharField(blank=True, max_length=250, null=True, validators=[elites_franchise_portal.common.validators.items_elites_code_validator])),
            ],
            options={
                'ordering': ['-brand_name'],
            },
        ),
        migrations.CreateModel(
            name='BrandItemType',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('pushed_to_edi', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.brand')),
            ],
            options={
                'ordering': ('brand__brand_name', 'item_type__type_name'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('category_name', models.CharField(max_length=300)),
                ('category_code', models.CharField(blank=True, max_length=250, null=True, validators=[elites_franchise_portal.common.validators.items_elites_code_validator])),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('barcode', models.CharField(max_length=250)),
                ('item_name', models.CharField(blank=True, max_length=250, null=True)),
                ('item_code', models.CharField(blank=True, max_length=250, null=True, validators=[elites_franchise_portal.common.validators.items_elites_code_validator])),
                ('make_year', models.IntegerField(blank=True, null=True)),
                ('pushed_to_edi', models.BooleanField(default=False)),
                ('create_inventory_item', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-item_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('type_name', models.CharField(max_length=250)),
                ('type_code', models.CharField(blank=True, max_length=250, null=True, validators=[elites_franchise_portal.common.validators.items_elites_code_validator])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
            options={
                'ordering': ['-type_name'],
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('units_name', models.CharField(max_length=300)),
                ('units_code', models.CharField(blank=True, max_length=250, null=True, validators=[elites_franchise_portal.common.validators.units_elites_code_validator])),
            ],
            options={
                'ordering': ['-units_name'],
            },
        ),
        migrations.CreateModel(
            name='UnitsItemType',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_itemtype', to='items.itemtype')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemtype_units', to='items.units')),
            ],
            options={
                'ordering': ('item_type__category__category_name', 'item_type__type_name', 'units__units_name'),
            },
        ),
        migrations.AddField(
            model_name='units',
            name='item_types',
            field=models.ManyToManyField(related_name='itemtype', through='items.UnitsItemType', to='items.itemtype'),
        ),
        migrations.CreateModel(
            name='ItemUnits',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('items_per_purchase_unit', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('purchases_units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_units', to='items.units')),
                ('sales_units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selling_units', to='items.units')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('model_name', models.CharField(max_length=250)),
                ('model_code', models.CharField(blank=True, max_length=250, null=True, validators=[elites_franchise_portal.common.validators.items_elites_code_validator])),
                ('brand_item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.branditemtype')),
            ],
            options={
                'ordering': ['-model_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=elites_franchise_portal.items.models.get_directory)),
                ('is_hero_image', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('attribute_type', models.CharField(choices=[('SPECIAL OFFER', 'SPECIAL OFFER'), ('WARRANTY', 'WARRANTY'), ('SPECIAL FEATURE', 'SPECIAL FEATURE'), ('SPECIFICATION', 'SPECIFICATION'), ('DESCRIPTION', 'DESCRIPTION')], max_length=300)),
                ('attribute_value', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'ordering': ['-attribute_type', '-attribute_value'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='items.itemmodel'),
        ),
        migrations.AddField(
            model_name='branditemtype',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtype'),
        ),
        migrations.AddField(
            model_name='brand',
            name='item_types',
            field=models.ManyToManyField(related_name='branditemtypes', through='items.BrandItemType', to='items.itemtype'),
        ),
        migrations.AddConstraint(
            model_name='unitsitemtype',
            constraint=models.UniqueConstraint(fields=('units', 'item_type'), name='unique_units_per_item_type'),
        ),
        migrations.AddConstraint(
            model_name='branditemtype',
            constraint=models.UniqueConstraint(fields=('brand', 'item_type'), name='unique_brand_per_type'),
        ),
    ]
