# Generated by Django 4.0.4 on 2022-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemunits',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='units',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
