# Generated by Django 4.1.1 on 2022-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemunits',
            name='quantity_of_sale_units_per_purchase_unit',
            field=models.FloatField(default=1),
        ),
    ]
