# Generated by Django 4.0.4 on 2022-08-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_itemmodel_brand_item_type_itemmodel_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='create_inventory_item',
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
