# Generated by Django 4.1.1 on 2023-02-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0002_initial'),
        ('items', '0003_alter_units_units_name_alter_units_units_quantity'),
        ('debit', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
        migrations.AddField(
            model_name='purchasesreturn',
            name='purchase_item',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, to='credit.purchaseitem'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='items.item'),
        ),
        migrations.AddField(
            model_name='inventoryinventoryitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryinventoryitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_items',
            field=models.ManyToManyField(related_name='inventoryinventoryitems', through='debit.InventoryInventoryItem', to='debit.inventoryitem'),
        ),
    ]
