# Generated by Django 4.0.4 on 2022-08-27 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import elites_franchise_portal.common.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('reg_no', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=300)),
                ('main_branch_code', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('is_main', models.BooleanField(default=True)),
                ('elites_code', models.CharField(blank=True, max_length=300, null=True, unique=True, validators=[elites_franchise_portal.common.validators.franchise_elites_code_validator])),
                ('partnership_type', models.CharField(choices=[('AGENT', 'AGENT'), ('SHOP', 'SHOP'), ('SUPERMARKET', 'SUPERMARKET')], default='SHOP', max_length=300)),
                ('dissolution_date', models.DateField(blank=True, db_index=True, null=True)),
                ('dissolution_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('social_platform', models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('TWITTER', 'TWITTER'), ('INSTAGRAM', 'INSTAGRAM'), ('WHATSAPP', 'WHATSAPP')], max_length=250)),
                ('link', models.URLField()),
                ('franchise', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, related_name='platform_franchise_name', to='franchises.franchise')),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FranchiseContacts',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('franchise', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, related_name='contact_franchise_name', to='franchises.franchise')),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'abstract': False,
            },
        ),
    ]
