# Generated by Django 4.1.1 on 2022-11-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
