# Generated by Django 4.0.4 on 2022-08-10 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('catalog', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('inventory_code', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('check_store', models.BooleanField(default=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
            options={
                'ordering': ['item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('store_code', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
            options={
                'ordering': ['item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='StoreRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('opening_quantity', models.FloatField(default=0.0)),
                ('opening_total_amount', models.FloatField(default=0.0)),
                ('record_type', models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE')], default='ADD', max_length=300)),
                ('quantity_recorded', models.FloatField()),
                ('removal_type', models.CharField(blank=True, choices=[('INVENTORY', 'INVENTORY'), ('DAMAGES', 'DAMAGES'), ('SUPPLIES', 'SUPPLIES')], max_length=300, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('disposing_price', models.FloatField(blank=True, null=True)),
                ('total_amount_recorded', models.FloatField(blank=True, null=True)),
                ('closing_quantity', models.FloatField(blank=True, null=True)),
                ('closing_total_amount', models.FloatField(blank=True, null=True)),
                ('removal_quantity_leaving_store', models.FloatField(blank=True, default=0, null=True)),
                ('removal_quantity_remaining_in_store', models.FloatField(blank=True, default=0, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('sale_type', models.CharField(choices=[('INSTANT', 'INSTANT'), ('INSTALLMENT', 'INSTALLMENT')], default='INSTANT', max_length=300)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_sold', models.FloatField()),
                ('opening_stock_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('closing_stock_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('opening_stock_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('closing_stock_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_cleared', models.BooleanField(default=False)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.sale', verbose_name='sales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('opening_stock_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('opening_stock_total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('record_type', models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE')], max_length=300)),
                ('quantity_recorded', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_amount_recorded', models.FloatField(blank=True, null=True)),
                ('removal_type', models.CharField(blank=True, choices=[('SALES', 'SALES'), ('DAMAGES', 'DAMAGES')], max_length=300, null=True)),
                ('closing_stock_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('closing_stock_total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('quantity_of_stock_on_display', models.FloatField()),
                ('quantity_of_stock_in_store', models.FloatField(blank=True, null=True)),
                ('quantity_of_stock_on_sale', models.FloatField(blank=True, null=True)),
                ('quantity_sold', models.FloatField(blank=True, null=True)),
                ('remaining_stock_total_amount', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventoryitem')),
            ],
            options={
                'ordering': ['inventory_item__item__item_name'],
            },
        ),
    ]
