# Generated by Django 4.1.1 on 2022-11-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='closing_stock_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='closing_stock_quantity',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='opening_stock_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='opening_stock_quantity',
        ),
    ]
