# Generated by Django 4.1.1 on 2022-11-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='updated_catalog',
            field=models.BooleanField(default=False),
        ),
    ]
