# Generated by Django 4.0.4 on 2022-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CANCELED', 'CANCELED'), ('REJECTED', 'REJECTED'), ('CONFIRMED', 'CONFIRMED'), ('PROCESSED', 'PROCESSED')], default='PENDING', max_length=300),
        ),
    ]
