# Generated by Django 4.1.1 on 2022-10-23 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_remove_purchase_item_remove_purchase_move_in_bulk_and_more'),
        ('debit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesReturn',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('quantity_returned', models.FloatField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('purchase_item', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, to='credit.purchaseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
