# Generated by Django 4.1.1 on 2022-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0002_inventoryrecord_updated_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
