# Generated by Django 4.0.4 on 2022-08-23 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_itemmodel_brand_item_type_itemmodel_brand_and_more'),
        ('debit', '0002_sale_sale_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('inventory_name', models.CharField(max_length=300)),
                ('inventory_code', models.CharField(blank=True, max_length=300, null=True)),
                ('inventory_type', models.CharField(choices=[('EXCESS', 'EXCESS'), ('SERVICE', 'SERVICE'), ('AVAILABLE', 'AVAILABLE'), ('ALLOCATED', 'ALLOCATED'), ('DECOUPLING', 'DECOUPLING'), ('THEORETICAL', 'THEORETICAL'), ('RAW MATERIALS', 'RAW MATERIALS'), ('FINISHED GOODS', 'FINISHED GOODS'), ('MAINTENANCE, REPAIR AND OPERATING', 'MRO'), ('SAFETY STOCK', 'SAFETY STOCK'), ('WORKING STOCK', 'WORKING STOCK'), ('ANTICIPATORY STOCK', 'ANTICIPATORY STOCK'), ('PSYCHIC STOCK', 'PSYCHIC STOCK'), ('PACKING MATERIALS', 'PACKING MATERIALS'), ('IN TRANSIT STOCK', 'IN TRANSIT STOCK'), ('WORK IN PROGRESS', 'WORK IN PROGRESS')], default='WORKING STOCK', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('pushed_to_edi', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryInventoryItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('pushed_to_edi', models.BooleanField(default=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('warehouse_code', models.CharField(blank=True, max_length=250, null=True)),
                ('warehouse_name', models.CharField(max_length=300)),
                ('warehouse_type', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('BONDED', 'BONDED'), ('SMART', 'SMART'), ('CONSOLIDATED', 'CONSOLIDATED'), ('COOPERATIVE', 'COOPERATIVE'), ('GOVERNMENT', 'GOVERNMENT'), ('DISTRIBUTION CENTER', 'DISTRIBUTION CENTER')], default='PRIVATE', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('pushed_to_edi', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
            options={
                'ordering': ['item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('opening_quantity', models.FloatField(default=0.0)),
                ('opening_total_amount', models.FloatField(default=0.0)),
                ('record_type', models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE')], default='ADD', max_length=300)),
                ('quantity_recorded', models.FloatField()),
                ('removal_type', models.CharField(blank=True, choices=[('INVENTORY', 'INVENTORY'), ('DAMAGES', 'DAMAGES'), ('SUPPLIES', 'SUPPLIES')], max_length=300, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('disposing_price', models.FloatField(blank=True, null=True)),
                ('total_amount_recorded', models.FloatField(blank=True, null=True)),
                ('closing_quantity', models.FloatField(blank=True, null=True)),
                ('closing_total_amount', models.FloatField(blank=True, null=True)),
                ('removal_quantity_leaving_warehouse', models.FloatField(blank=True, default=0, null=True)),
                ('removal_quantity_remaining_in_warehouse', models.FloatField(blank=True, default=0, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.warehouse')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.warehouseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseWarehouseItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('franchise', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('pushed_to_edi', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.warehouse')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.warehouseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='storerecord',
            name='store',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='check_store',
            new_name='check_warehouse',
        ),
        migrations.RenameField(
            model_name='inventoryrecord',
            old_name='quantity_of_stock_in_store',
            new_name='quantity_of_stock_in_warehouse',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory_code',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='StoreRecord',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_items',
            field=models.ManyToManyField(related_name='warehousewarehouseitems', through='debit.WarehouseWarehouseItem', to='debit.warehouseitem'),
        ),
        migrations.AddField(
            model_name='inventoryinventoryitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_items',
            field=models.ManyToManyField(related_name='inventoryinventoryitems', through='debit.InventoryInventoryItem', to='debit.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='inventory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='debit.inventory'),
            preserve_default=False,
        ),
    ]
