# Generated by Django 4.0.4 on 2022-08-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0002_salerecord_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='encounter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
