# Generated by Django 4.1.1 on 2022-11-03 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0003_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
