# Generated by Django 4.0.4 on 2022-08-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0003_inventory_inventoryinventoryitem_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
