# Generated by Django 4.0.4 on 2022-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0004_inventory_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='record_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('EXCESS', 'EXCESS'), ('SERVICE', 'SERVICE'), ('AVAILABLE', 'AVAILABLE'), ('ALLOCATED', 'ALLOCATED'), ('DECOUPLING', 'DECOUPLING'), ('THEORETICAL', 'THEORETICAL'), ('RAW MATERIALS', 'RAW MATERIALS'), ('FINISHED GOODS', 'FINISHED GOODS'), ('MAINTENANCE, REPAIR AND OPERATING', 'MRO'), ('SAFETY STOCK', 'SAFETY STOCK'), ('WORKING STOCK', 'WORKING STOCK'), ('ANTICIPATORY STOCK', 'ANTICIPATORY STOCK'), ('PSYCHIC STOCK', 'PSYCHIC STOCK'), ('PACKING MATERIALS', 'PACKING MATERIALS'), ('IN TRANSIT STOCK', 'IN TRANSIT STOCK'), ('WORK IN PROCESS', 'WORK IN PROCESS')], default='WORKING STOCK', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='quantity_of_stock_on_display',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='record_type',
            field=models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE')], default='ADD', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='removal_type',
            field=models.CharField(blank=True, choices=[('SALES', 'SALES'), ('DAMAGES', 'DAMAGES'), ('RETURNS', 'RETURNS'), ('SUPPLIES', 'SUPPLIES'), ('INVENTORY', 'INVENTORY')], max_length=300, null=True),
        ),
    ]
