# Generated by Django 4.1.1 on 2022-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0004_salerecord_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='encounter',
            new_name='data',
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
