# Generated by Django 4.0.4 on 2022-08-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0004_inventory_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='is_default',
            new_name='is_master',
        ),
    ]
