# Generated by Django 4.1.1 on 2022-11-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('debit', '0005_rename_encounter_sale_data_sale_receipt_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleRecord',
            new_name='SaleItem',
        ),
    ]
