# Generated by Django 4.1.1 on 2022-11-07 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0006_rename_salerecord_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesreturn',
            name='return_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
