# Generated by Django 4.1.1 on 2023-02-08 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import elites_retail_portal.common.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('catalog_name', models.CharField(max_length=300)),
                ('catalog_code', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_standard', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('deactivated_on', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True, null=True)),
                ('catalog_type', models.CharField(choices=[('ON SITE', 'ON SITE'), ('AGENTS', 'AGENTS'), ('CUSTOMERS', 'CUSTOMERS')], default='ON SITE', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('pushed_to_edi', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogCatalogItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('pushed_to_edi', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('marked_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('threshold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('currency', models.CharField(choices=[('KSH', 'KSH')], default='KSH', max_length=250)),
                ('quantity', models.FloatField(default=0)),
                ('on_display', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pushed_to_edi', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-marked_price', '-selling_price', '-inventory_item'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('section_name', models.CharField(max_length=250)),
                ('section_code', models.CharField(blank=True, max_length=250, null=True, validators=[elites_retail_portal.common.validators.items_enterprise_code_validator])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-section_name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItemAuditLog',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('audit_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('quantity_before', models.FloatField(blank=True, default=0, null=True)),
                ('quantity_recorded', models.FloatField(blank=True, default=0, null=True)),
                ('quantity_after', models.FloatField(blank=True, default=0, null=True)),
                ('selling_price_before', models.FloatField(blank=True, default=0, null=True)),
                ('selling_price_recorded', models.FloatField(blank=True, default=0, null=True)),
                ('selling_price_after', models.FloatField(blank=True, default=0, null=True)),
                ('marked_price_before', models.FloatField(blank=True, default=0, null=True)),
                ('marked_price_recorded', models.FloatField(blank=True, default=0, null=True)),
                ('marked_price_after', models.FloatField(blank=True, default=0, null=True)),
                ('threshold_price_before', models.FloatField(blank=True, default=0, null=True)),
                ('threshold_price_recorded', models.FloatField(blank=True, default=0, null=True)),
                ('threshold_price_after', models.FloatField(blank=True, default=0, null=True)),
                ('discount_amount_before', models.FloatField(blank=True, default=0, null=True)),
                ('discount_amount_recorded', models.FloatField(blank=True, default=0, null=True)),
                ('discount_amount_after', models.FloatField(blank=True, default=0, null=True)),
                ('record_type', models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE')], max_length=300)),
                ('operation_type', models.CharField(choices=[('CREATE CATALOG ITEM', 'CREATE CATALOG ITEM'), ('UPDATE CATALOG ITEM', 'UPDATE CATALOG ITEM'), ('CREATE INVENTORY RECORD', 'CREATE INVENTORY RECORD'), ('UPDATE INVENTORY RECORD', 'UPDATE INVENTORY RECORD')], max_length=300)),
                ('audit_type', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE')], max_length=300)),
                ('audit_source', models.CharField(choices=[('CATALOG ITEM', 'CATALOG ITEM'), ('INVENTORY RECORD', 'INVENTORY RECORD')], default='INVENTORY RECORD', max_length=300)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_item_audit_log', to='catalog.catalogitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
