# Generated by Django 4.1.1 on 2023-02-08 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import elites_retail_portal.procurement.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_alter_units_units_name_alter_units_units_quantity'),
        ('enterprises', '0002_enterprise_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('lpo_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lpo_number', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprises.staff')),
                ('supplier', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseorder_supplier', to='enterprises.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderScan',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('lpo_scan', models.FileField(blank=True, null=True, upload_to=elites_retail_portal.procurement.models.get_directory)),
                ('purchase_order', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.FloatField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_authorized', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprises.staff')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('purchase_order', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
