# Generated by Django 4.1.1 on 2023-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
